# Generated by Django 5.0.1 on 2024-04-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Homepage',
        ),
    ]
