# Generated by Django 5.0.1 on 2024-04-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customer_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='Customer',
        ),
    ]
