# Generated by Django 4.2.3 on 2023-11-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
