# Generated by Django 5.0.1 on 2024-03-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
