# Generated by Django 5.0.1 on 2024-03-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0008_customer_linkedin_customer_logo_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='my_field',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3')], max_length=20, null=True),
        ),
    ]
